### ISSUE TITLE
Show card number preference doesn't work

### ISSUE THREAD

**Issue by nikjft** [theodo/scrummer#21]
I tried disabling "show card numbers" and they still show up. Seems like that preference setting doesn't work.

![OURA | Trello 2023-11-15 14-13-28](https://github.com/theodo/scrummer/assets/828123/edef5e2a-e1dd-4a03-aabc-5090e3cc6c86)

**Comment by nikjft** [comment]
Looks like the preference to hide board points also doesn't work. Maybe there's something generally wrong with the prefs configuration?

**Comment by mbarberot** [comment]
I've fixed the show/hide card id in #17 but the pull request is still pending. 
Just looked the code for the show/hide board totals : it's not used but you can disable it with the show/hide column totals settings. 
i'm not sure if it's a feature or a bug.

**Comment by LeoAnesi** [comment]
Thank you @mbarberot for your PR, I just merged it and subitted new version for Chrome and Firefox.
Firefox is already out and the version is waiting for review in Chrome.

Closing the issue.
